site_name: Interactive Content Creation Documentation

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - csharp
        - javascript
        - xml
